#!/bin/bash
# rename to pre-commit in your hooks directory

cd $(git rev-parse --show-toplevel)
files="`git diff --cached --name-only`"
#files="`git log -1 --name-only --oneline | tail -n +2`"

currentYear=`date +%Y`
yearsToGoBack=5

for i in $files
do
  if [ -f $i ]
  then
    for (( j=1; j <= yearsToGoBack; j=j+1 ))
    do
      year=$((currentYear-j))
      sed -i "s/(c) $year/(c) $currentYear/g" $i
      git add $i
    done
  fi
done


format_file() {
  file="${1}"
  # ignore git deleted file
  if [ -f "${file}" ] ; then
    ext="${file##*.}"
    ext=$(echo $ext | tr [A-Z] [a-z])
    # only format C/C++ files
    if [[ ("${ext}" == "h") || ("${ext}" == "hpp") || ("${ext}" == "c") || ("${ext}" == "cpp") || ("${ext}" == "mm")]]; then
      clang-format-11 -i --style=file ${1}
    fi
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD` ; do
      format_file "${file}"
    done
    ;;
esac
